[package]
name = "sync-server"
version = "0.0.1"
edition = "2018"

[dependencies]
actix-web = "3.3.2"
base64 = "0.13.0"
futures = "0.3.17"
futures-util = "0.3.17"
serde = "1.0.130"
serde_json = "1.0.68"
tokio-test = "0.4.2"

[dev-dependencies]
actix-rt = "2.2.0"
