apiVersion: v1
kind: Service
metadata:
  name: client-pwa
spec:
  type: NodePort
  selector:
    app: client-pwa
  ports:
    - port: 80
      targetPort: 80
---
# Currently, there is nothing but client-pwa exposed, so ingress can be part of it here
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  defaultBackend:
    service:
      name: client-pwa
      port:
        number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-pwa
spec:
  selector:
    matchLabels:
      app: client-pwa
  replicas: 1
  template:
    metadata:
      labels:
        app: client-pwa
    spec:
      containers:
        - name: client-pwa
          image: [IMAGE]
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
